blank_issues_enabled: false
contact_links:
  - name: If you want to ask or report something else, you can do it privately
    url: https://twitter.com/yungsamd17
    about: You can DM me @yungsamd17 on X (formerly Twitter).
